/**
 * generated by Xtext 2.29.0
 */
package fr.n7.simplePDL.textSimplePDL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Work Sequence</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.simplePDL.textSimplePDL.WorkSequence#getPredecessor <em>Predecessor</em>}</li>
 *   <li>{@link fr.n7.simplePDL.textSimplePDL.WorkSequence#getSuccessor <em>Successor</em>}</li>
 * </ul>
 *
 * @see fr.n7.simplePDL.textSimplePDL.TextSimplePDLPackage#getWorkSequence()
 * @model
 * @generated
 */
public interface WorkSequence extends ProcessElement
{
  /**
   * Returns the value of the '<em><b>Predecessor</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Predecessor</em>' reference.
   * @see #setPredecessor(WorkDefinition)
   * @see fr.n7.simplePDL.textSimplePDL.TextSimplePDLPackage#getWorkSequence_Predecessor()
   * @model
   * @generated
   */
  WorkDefinition getPredecessor();

  /**
   * Sets the value of the '{@link fr.n7.simplePDL.textSimplePDL.WorkSequence#getPredecessor <em>Predecessor</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Predecessor</em>' reference.
   * @see #getPredecessor()
   * @generated
   */
  void setPredecessor(WorkDefinition value);

  /**
   * Returns the value of the '<em><b>Successor</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Successor</em>' reference.
   * @see #setSuccessor(WorkDefinition)
   * @see fr.n7.simplePDL.textSimplePDL.TextSimplePDLPackage#getWorkSequence_Successor()
   * @model
   * @generated
   */
  WorkDefinition getSuccessor();

  /**
   * Sets the value of the '{@link fr.n7.simplePDL.textSimplePDL.WorkSequence#getSuccessor <em>Successor</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Successor</em>' reference.
   * @see #getSuccessor()
   * @generated
   */
  void setSuccessor(WorkDefinition value);

} // WorkSequence
