/*
 * generated by Xtext 2.29.0
 */
package fr.n7.simplePDL.ui.tests;

import com.google.inject.Injector;
import fr.n7.simplePDL.xtext.ui.internal.XtextActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class TextSimplePDLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("fr.n7.simplePDL.TextSimplePDL");
	}

}
