/*
 * generated by Xtext 2.29.0
 */
package fr.n7.simplePDL;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class TextSimplePDLStandaloneSetup extends TextSimplePDLStandaloneSetupGenerated {

	public static void doSetup() {
		new TextSimplePDLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
