/*
 * generated by Xtext 2.29.0
 */
package fr.n7.simplePDL.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TextSimplePDLUiModule extends AbstractTextSimplePDLUiModule {

	public TextSimplePDLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
