/*
 * generated by Xtext 2.29.0
 */
package fr.n7.simplePDL.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractTextSimplePDLValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(fr.n7.simplePDL.textSimplePDL.TextSimplePDLPackage.eINSTANCE);
		return result;
	}
}
