/*
 * generated by Xtext 2.29.0
 */
package fr.n7.simplePDL.ide;


/**
 * Use this class to register ide components.
 */
public class TextSimplePDLIdeModule extends AbstractTextSimplePDLIdeModule {
}
